# Generated by Django 4.2.7 on 2023-11-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='location',
            name='account',
        ),
        migrations.RemoveField(
            model_name='locationprofile',
            name='brand',
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='clover.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clover.brand'),
            preserve_default=False,
        ),
    ]
