# Generated by Django 4.2.7 on 2023-11-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clover', '0002_rename_name_brand_brand_remove_location_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='personprofile',
            old_name='mobile_phone_number',
            new_name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='domainprofile',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='domainprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='domainprofile',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='domainprofile',
            name='nameservers',
        ),
        migrations.RemoveField(
            model_name='domainprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='domainprofile',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='person',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='social_security_number',
        ),
        migrations.AddField(
            model_name='domain',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clover.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personprofile',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
